JohnSundell/Plot

- Sources/Plot/API/HTMLAttributes.swift
- Tests/PlotTests/HTMLTests.swift
This implements the `aria-controls` attribute which is used to establish parent -> child relationship between nodes.
https://www.w3.org/TR/wai-aria-1.1/#aria-controls
https://www.accessibilityresources.org/aria-controls
> Implement `aria-controls` accessibility attribute

- Tests/PlotTests/HTMLTests.swift
Turns out the only test covering this element was deleted before public release, so make `testTable` also cover `<th>` to restore 100% coverage.
> HTML: Unit test <th> element

- Sources/Plot/API/HTMLAttributes.swift
- Tests/PlotTests/HTMLTests.swift
And the `aria` aria saga continues…
I'm using this one on my site to determine whether a css-only menu is in it's expanded state or not. By using this I was able to leverage the power of responsiveness™  and remove the last pieces of JavaScript on the site.
Reference: 
https://www.w3.org/WAI/GL/wiki/Using_aria-expanded_to_indicate_the_state_of_a_collapsible_element
> Implement `aria-expanded` accessibility attribute

- Sources/Plot/API/HTMLAttributes.swift
- Sources/Plot/API/HTMLComponents.swift
- Sources/Plot/API/PodcastAttributes.swift
- Sources/Plot/API/PodcastComponents.swift
- Sources/Plot/API/PodcastElements.swift
- Sources/Plot/API/RSSAttributes.swift
- Sources/Plot/API/RSSElements.swift
- Sources/Plot/API/SiteMapElements.swift
- Sources/Plot/API/URLRepresentable.swift
- Tests/PlotTests/HTMLTests.swift
This change enables `URL` values to be directly passed to DSL APIs that accept a URL, such as `.src()`, `.href()`, and so on. Rather than having to implement overloads for each API, and rather than having to “pollute” standard types like `String` and `URL` with new properties/methods, this
implementation piggybacks on the `CustomStringConvertible` protocol - but still includes a “marker” protocol called `URLRepresentable` to prevent *any* string convertible type from being passed to these APIs.
> Enable URLs to be passed directly to attributes and components

- Sources/Plot/API/HTML.swift
- Sources/Plot/API/HTMLAttributes.swift
- Sources/Plot/API/HTMLElements.swift
- Tests/PlotTests/HTMLTests.swift
Adds support for `<textarea>` HTML element. 
Create `TextAreaContext` which provides `rows`, `cols`, `required` and `autofocus` attributes. It takes a list of Nodes so you can add `.text` node.
Included `textarea` in testForm() test that already exists.
At the same time added a `required` attribute to `Attribute where Context == HTML.InputContext`.
> Add support for textarea element

- Sources/Plot/API/ControlFlow.swift
Mark `unwrap` and `forEach` as `rethrows` to allow any closure passed into those APIs to throw.
> Control flow: Support throwing closures

- Sources/Plot/Internal/String+Escaping.swift
- Tests/PlotTests/NodeTests.swift
This patch makes sure that any HTML entities contained within a string passed to `Node.text` won’t be double-escaped, by making the string escaping code read ahead when encountering an ampersand, and then filling in any pending text following it once it has determined that it wasn’t the start of an HTML entity. With this approach, the performance impact on the escaping code is very low, since it retains close to `O(N)` time complexity.
> Node: Prevent HTML entities from being double-escaped

- Sources/Plot/API/PodcastElements.swift
- Tests/PlotTests/PodcastFeedTests.swift
This patch fixes the podcast duration padding code, to make sure that a leading zero is always added for hour, minute or second values that are less than 10.
> Podcast: Correctly pad duration numbers lower than 10

- Sources/Plot/API/HTMLAttributes.swift
- Sources/Plot/API/HTMLElements.swift
- Tests/PlotTests/HTMLTests.swift
- Tests/PlotTests/NodeTests.swift
This change contains minor fixes to documentation wording, removal of unnecessary whitespace, and restore’s Plot’s 100% unit test coverage.
> Minor documentation fixes + restore 100% test coverage

- Sources/Plot/API/Indentation.swift
- Sources/Plot/API/PodcastType.swift
- Tests/PlotTests/IndentationTests.swift
- Tests/PlotTests/LinuxCompatibility.swift
- Tests/PlotTests/XCTestManifests.swift
This will enable tools built on top of Plot (like Publish) to encode types containing these kinds of values. Also improve the Linux compatibility tooling to detect if a new test case was added only on Apple Platforms.
> Indentation + PodcastType: Make Equatable and Codable

- README.md
- Sources/Plot/API/ControlFlow.swift
- Sources/Plot/API/HTML.swift
- Sources/Plot/API/HTMLAttributes.swift
- Sources/Plot/API/HTMLComponents.swift
- Tests/PlotTests/HTMLTests.swift
This PR adds the `.integrity(_:String)` attribute to `<link>` and `<script>` elements and also adds an overload to the `.stylesheet` component to accept it as a second, named argument.
Also in doing this I added `.unwrap` to `Attribute` (whereas it was initially only on `Node`). I didn't go ahead and add `.if` and `.forEach` but they may be nice to have.
I also added a test for the three use cases.
---
[Mozilla](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity):
>Subresource Integrity (SRI) is a security feature that enables browsers to verify that resources they fetch (for example, from a CDN) are delivered without unexpected manipulation. It works by allowing you to provide a cryptographic hash that a fetched resource must match.
> Add Support for Subresource Integrity (SRI)

- Tests/PlotTests/IndentationTests.swift
This adds a test that verifies that attempting to decode an `Indentation.Kind` with an invalid underlying string throws an error, which restores Plot’s 100% unit testing coverage.
> Indentation: Test decoding error for invalid kind

- Sources/Plot/API/HTMLAttributes.swift
- Sources/Plot/API/Language.swift
- Tests/PlotTests/HTMLTests.swift
- Merge recent link attribute APIs with existing extension.
- Documentation fixes and improvements.
- CamelCase `x-default` language as `xDefault`.
- Merge tests that were testing the same code paths.
- Improve test naming and readability.
> HTML links: Post-merge fixes

- Sources/Plot/API/HTMLAttributes.swift
- Sources/Plot/API/HTMLElements.swift
- Tests/PlotTests/HTMLTests.swift
1. Added `async` attribute for `HTML.ScriptContext`
2. Added `defer` attribute for `HTML.ScriptContext`
> Added async and defer attributes for script

- Sources/Plot/API/Node.swift
In Node.swift fixed parameter naming comments. E.g. in the below on line 3 "nodes" -> "attributes"
/// Create a custom element with a given name and an array of attributes.
/// - parameter name: The name of the element to create.
/// - parameter nodes: The attributes to add to the element.
static func element<C>(named name: String, attributes: [Attribute<C>]) -> Node {
.element(Element(name: name, nodes: attributes.asNodes()))
> Fix parameter naming comments in Node.swift

- Sources/Plot/API/HTML.swift
- Sources/Plot/API/HTMLAttributes.swift
- Sources/Plot/API/HTMLElements.swift
- Tests/PlotTests/HTMLTests.swift
This change adds support for `<picture>`, and its associated `srcset` and `media` attributes. This is done by creating a new `HTMLSourceListContext` protocol which `<picture>` shares with `<audio>` and `<video>`, enabling maximum code reuse while still preserving type safety. Since an `<img>` element can also appear inside of `<picture>`, image tags are now constrained to a new `HTMLImageContainerContext`, which `HTML.BodyContext` also adopts.
> Add support for the HTML <picture> element

- Sources/Plot/API/HTMLAttributes.swift
- Tests/PlotTests/HTMLTests.swift
This PR adds support for the `aria-hidden` accessibility attribute, which [instructs the browser to remove an element and all of its children from the accessibility tree](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-hidden_attribute).
Sorry for sending so many PRs-I just noticed these missing attributes while setting up a site so I thought I'd contribute back 👍
> Add support for the aria-hidden accessibility attribute

- Sources/Plot/API/HTMLAttributes.swift
- Tests/PlotTests/HTMLTests.swift
This PR adds support for the `placeholder` attribute on input fields, which [specifies a short hint that describes the expected value of an input field](https://www.w3schools.com/tags/att_input_placeholder.asp).
> Add support for placeholder attribute on input fields

- Sources/Plot/API/HTMLAttributes.swift
- Tests/PlotTests/HTMLTests.swift
This PR adds support for the `novalidate` form attribute, which [specifies that the form-data (input) should not be validated when submitted](https://www.w3schools.com/tags/att_form_novalidate.asp).
> Add novalidate form attribute

- Sources/Plot/API/HTMLElements.swift
- Tests/PlotTests/HTMLTests.swift
The <aside> tag defines some content aside from the content it is placed in.
`testAside()` passes successfully.
> Add support for the <aside> tag

- Sources/Plot/API/HTMLElements.swift
- Tests/PlotTests/HTMLTests.swift
This change moves the APIs for creating what can be seen as “form-specific” HTML elements (such as `<input>` and `<fieldset>`) from an extension constrained to `HTML.FormContext` to the main `HTML.BodyContext` instead. This enables such elements to be mixed and matched with other body elements, such as `<div>`.
While such elements might most often appear within forms, there’s nothing within the HTML spec that enforces that, so neither should Plot.
Thanks to @daveverwer for the test case code 🙌
> HTML: Constrain <form>-specific elements to BodyContext

- Sources/Plot/API/HTMLElements.swift
- Tests/PlotTests/HTMLTests.swift
This might seem like an outdated/visual type element (like `i`, and `b`) but it’s not. It’s for small print and that kind of thing.
HTML spec here: https://html.spec.whatwg.org/#the-small-element
> Add the small element.

- Sources/Plot/API/HTMLElements.swift
- Tests/PlotTests/HTMLTests.swift
Adding just a test to start a discussion on this. It's certainly valid to add all sorts of attributes to a `<hr>` element, with `class` being just one of them.
I'm not entirely sure how to fix this, and almost certainly this test is too specific as I bet there's a lot of the closed elements that can take a great many attributes, but it should be able to be the start of a discussion.
> Enable attributes to be attached to <hr> elements

- Sources/Plot/API/HTML.swift
- Sources/Plot/API/HTMLAttributes.swift
- Sources/Plot/API/HTMLElements.swift
- Tests/PlotTests/HTMLTests.swift
Again, more to start a discussion than anything. I'm sure this test is way too specific, but `<div>` elements should be able to accept `title` attributes.
> Add title support for HTML body elements

- Sources/Plot/API/HTMLAttributes.swift
- Tests/PlotTests/HTMLTests.swift
The label attribute allows you to show the user a label other than the underlying form value
https://html.spec.whatwg.org/#the-option-element
> (feat) added label attribute to \<option\>

- Sources/Plot/API/HTML.swift
- Tests/PlotTests/HTMLTests.swift
`<img>` tag works with `width` and `height` attribute. And will set the image dimension in px. Make the `ImageContext` adopt `HTMLDimensionContext` so we could change the image size without CSS.
```
.img(
.src("/images/sample.png"),
.width(44),
.height(44)
)
```
> Make img tag supports width and height attribute

- Sources/Plot/API/Attribute.swift
- Sources/Plot/Internal/AnyAttribute.swift
- Sources/Plot/Internal/ElementRenderingBuffer.swift
- Tests/PlotTests/HTMLComponentTests.swift
When adding an attribute that should be appended to any existing one, first check if either the existing or new attribute contain an empty value, and if so, don't perform the append. Otherwise, we'll end up with extra whitespace within attribute values. Also, slight cleanup of the attribute handling logic within `ElementRenderingBuffer`, to make the conditionals a bit more clear.
> Prevent empty attribute values from being appended

- Sources/Plot/API/Node.swift
- Tests/PlotTests/HTMLComponentTests.swift
When an attribute is added to a component that acts as a wrapper for an element-based component, that attribute is now added directly to the wrapped, underlying element. That makes it possible to append things like class names to existing, custom components.
> Make it possible to add attributes to wrapper components

- Sources/Plot/API/Node.swift
- Tests/PlotTests/HTMLComponentTests.swift
Make it possible to append attributes to the member elements of a `ComponentGroup`, when such a group is nested within a custom wrapper component.
> Enable attributes to be appended to members of nested component groups

- Sources/Plot/Internal/ElementRenderingBuffer.swift
- Sources/Plot/Internal/Renderer.swift
- Tests/PlotTests/DocumentTests.swift
Plot 0.9.0 introduced a minor regression for documents that are rendered with indentation, in that plain text nodes would always be rendered on a new line. This patch fixes that by differentiating between plain text output and element-based output, and only the latter causes a new line to be inserted, preserving the previous rendering behavior.
Components that are made up of just plain text also get this behavior, and the unit test that verifies indented documents has been expanded to also cover these cases.
> Fix text rendering regression for indented documents

- Sources/Plot/API/HTMLAttributes.swift
- Tests/PlotTests/HTMLTests.swift
The [title attribute](https://html.spec.whatwg.org/#the-title-attribute) is listed under [Global attributes](https://html.spec.whatwg.org/#global-attributes) and is useful in the `head`, for example for `link` elements.
> Made the `title` attribute into a global attribute.

- Sources/Plot/API/HTMLAttributes.swift
- Tests/PlotTests/HTMLTests.swift
It may feel like `spellcheck` should be specific to `form` or `input` elements, but it's global. Probably because of `contenteditable`, which Plot doesn't support yet, but I'm sure it will some day.
For proof, see [this section](https://html.spec.whatwg.org/#global-attributes) of the spec.
> Added a global `spellcheck` attribute and tests with common use cases

- Sources/Plot/API/HTMLAttributes.swift
- Tests/PlotTests/HTMLComponentTests.swift
- Tests/PlotTests/HTMLTests.swift
I'm expecting a bit of a discussion around this one! So, here's my justification. The [HTML spec](https://html.spec.whatwg.org/) has this to say about [boolean attributes](https://html.spec.whatwg.org/#boolean-attributes):
> A number of attributes are boolean attributes. The presence of a boolean attribute on an element represents the true value, and the absence of the attribute represents the false value.
It then gives an example of rendering them as this:
```html
<label><input type=checkbox checked name=cheese disabled> Cheese</label>
```
It does then go to say that they are also valid with values, or with empty values, but this functionality can be misleading. For example, all of these `<div>` elements will be rendered hidden:
```html
<div hidden></div>
<div hidden=""></div>
<div …
```
> Boolean attributes

- Sources/Plot/API/HTMLAttributes.swift
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture#the_type_attribute
> Adding `type` attribute to PictureSourceContext

- Sources/Plot/API/HTMLAnchorRelationship.swift
I was recently trying to add some `rel=me` links to my site, and noticed that the `HTMLAnchorRelationship` was a fixed enum with only a handful of options. I considered adding all of the official attributes to the enum, along with `me`, but figured it might be more useful to allow any attribute value to be used. 
My PR replaces the enum with a struct that conforms to `RawRepresentable`, and includes static properties for all of the attributes from W3C Schools. The change is additive and should be compatible with existing code. 
New attributes can be defined by users for their own sites by extending the struct: 
```swift
extension HTMLAnchorRelationship {
static let me: HTMLAnchorRelationship = "me"
}
```
> Replace HTMLAnchorRelationship with RawRepresentable struct

- Sources/Plot/API/Language.swift
Many of the same characters look different in traditional Chinese and simplified Chinese, so it is necessary to specify which Chinese they are.
> Add languages.

- README.md
Added a missing `swift` in codeblock to make things slightly easier to read.
> Update README.md to mark a codeblock as being `swift`

- Sources/Plot/API/ComponentAttributes.swift
- Sources/Plot/API/Directionality.swift
- Sources/Plot/API/HTMLAttributes.swift
- Tests/PlotTests/HTMLComponentTests.swift
- Tests/PlotTests/HTMLTests.swift
Since I will be using this package to build my personal website, which will be supporting English and Arabic, I figured the best way to thank you was to add this small contribution.
I added the ability to add [the `dir` attribute](https://html.spec.whatwg.org/#the-dir-attribute) in both the `Node` and `Component` based APIs.
It is a global attribute that can be added to any HTML elemnt (technically any element including non-HTML, but I didn't focuse on XML in this PR).
I added a new enum called `Directionality` (the name is inspired from the spec linked above) to hold the three possible values. I made the case names clearer to read and added the actual HTML values as a raw value to each case.
```swift
public enum Directionality: String {
case leftToRight = "ltr"
case rightToLeft = "rtl" …
```
> Add the dir HTML attribute

- Sources/Plot/API/HTMLComponents.swift
- Sources/Plot/API/HTMLViewportFitMode.swift
- Tests/PlotTests/HTMLTests.swift
`viewport-fit` is important for designing websites for iPhones with notches, see https://webkit.org/blog/7929/designing-websites-for-iphone-x/
Usage:
```swift
.viewport(.accordingToDevice, fit: .cover)
```
> Add viewport-fit to viewport meta tag

- README.md
- Sources/Plot/API/HTMLAttributes.swift
- Sources/Plot/API/HTMLComponents.swift
- Tests/PlotTests/HTMLTests.swift
Based on [official site](https://ogp.me)
All meta attributes with og:... content should use "property" name
> Compatibility with Open Graph protocol

- Sources/Plot/API/HTMLAttributes.swift
- Tests/PlotTests/HTMLTests.swift
The crossorigin attribute is needed for things like Google fonts where you should link to it like below:
```
…
<link rel=“preconnect” href=“http://foo.com” crossorigin />
…
```
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link#attributes
At the moment doing this means manually creating an `Attribute` instance but this would be cleaner.
> Add crossorigin link attribute

- Sources/Plot/API/HTML.swift
- Sources/Plot/API/HTMLComponents.swift
- Sources/Plot/API/HTMLElements.swift
- Tests/PlotTests/HTMLComponentTests.swift
- Tests/PlotTests/HTMLTests.swift
According to the HTML spec: // https://html.spec.whatwg.org/multipage/grouping-content.html#the-dl-element
> The `<div>` element wraps a group, that is part of a term-description group in a description list (`<dl>` element).
The proposed solution (using `dlDiv` instead of `div`) is a workaround for the current requirement for `ElementDefinition`.
> Extend dl with div wrapped groups

- Sources/Plot/API/HTMLComponents.swift
- Tests/PlotTests/HTMLTests.swift
Hi all,
This change is quite simple but something that is quite nice to have.
The tag twitter:site is used to identify the site by its Twitter handle (for example the @ SwiftBySundell twitter account) when shown in a card. See the [documentation](https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/markup)
I added a new node .twitterUsername(_) to set the Twitter username to be associated with the page.
(This is a replacement for #85 as that one was messed up with what commits were included)
> Add twitter:site meta tag
